### ISSUE TITLE
tidyquant theme

### ISSUE THREAD

**Issue by mdancho84** [jrnold/ggthemes#103]
Hi @jrnold,

I'm the creator of the `tidyquant` package. I have a `theme_tq()`, `palette_light()`, `palette_green()`, `palette_dark()`, `scale_color_tq()`, and `scale_fill_tq()` within the tidyquant package. Would you want to include any of the palettes and/or themes in `ggthemes`?

Here's the link to the tidyquant package: https://github.com/business-science/tidyquant

Thanks, Matt

**Comment by jrnold** [comment]
tidyquant looks really cool! Thanks for bringing it to my attention. However, I think the themes and scales for tidyquant should stay with that package. Is there a particular reason you wanted them in ggthemes?

**Comment by mdancho84** [comment]
Thank you! The reason is because I teach a number of courses and right now I’m having the students load in tidyquant (has a lot of dependencies) just to get the themes in a lot of cases. The themes are designed for business plotting. However it might be better to have these in a package like ggthemes to reduce dependencies and give a larger audience access to the palettes, scales, theme_tq(), etc.

**Comment by jrnold** [comment]
Sorry for the delay in getting back to you. Sure; that makes sense.  I'm going to add you as a collaborator, so you can merge your changes into ggthemes and also continue to maintain the tidyquant theme.s

**Comment by jrnold** [comment]
Closing this because I'm not looking to add additional themes to this package. This is in maintenance mode where I'm not adding new features.
