### ISSUE TITLE
Add topic: ggplot2-themes

### ISSUE THREAD

**Issue by katrinleinweber** [jrnold/ggthemes#114]
Thanks for publishing this! I think it would be better findable, if displayed on [GitHub.com/topics/ggplot2-themes](https://github.com/topics/ggplot2-theme), please consider [adding that topic](https://help.github.com/articles/about-topics/) to this repo. Thank you :-)

**Comment by jrnold** [comment]
Good idea. Thanks!

**Comment by katrinleinweber** [comment]
You're welcome!
