### ISSUE TITLE
geom_tufteboxplot  - Error on continuous x 

### ISSUE THREAD

**Issue by tjebo** [jrnold/ggthemes#117]
`ggthemes::geom_tufteboxplot` throws an error on continuous x - This is for both ungrouped and grouped data.

>Error in has_groups(data) : could not find function "has_groups"

[A similar issue was recently reported in `geom_sina`](https://github.com/thomasp85/ggforce/issues/35)

`geom_boxplot` works:
  ``` r
library(ggplot2)
library(ggthemes)

foo <- data.frame(x = rep(1:5,5), y = rnorm(25))

ggplot(foo) + 
  geom_boxplot(aes(x, y, group = x)) 
```

![](https://i.imgur.com/AVznMdt.png)

`geom_tufteplot` doesn't work:
``` r
ggplot(foo) + 
geom_tufteboxplot(aes(x, y, group = x)) 
#> Error in has_groups(data): could not find function "has_groups"
```

<sup>Created on 2020-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I've got ggplot2_3.2.1 and ggthemes_4.2.0 and installed.

**Comment by emallickhossain** [comment]
I found that converting x to a factor helped:

```
library(ggplot2)
library(ggthemes)
set.seed(111)

foo <- data.frame(group = rep(1:5,5), value = rnorm(25))

ggplot(foo) + 
  geom_tufteboxplot(aes(as.factor(group), value)) 
```

![image](https://user-images.githubusercontent.com/12176934/88717815-19fd1900-d0ef-11ea-8824-7222f6b5c427.png)



There is a fundamental problem when x is continuous as you outline. For example, if I simply want to have horizontal boxplots, it breaks:

```
ggplot(foo) + 
  geom_tufteboxplot(aes(y = value, color = as.factor(group))) 
```
![image](https://user-images.githubusercontent.com/12176934/88717924-40bb4f80-d0ef-11ea-9929-30e10216e9c2.png)

```
ggplot(foo) + 
  geom_tufteboxplot(aes(x = value, color = as.factor(group))) 
```

> Error in has_groups(data) : could not find function "has_groups"

My workaround is to simply flip the original plot:

```
ggplot(foo) + 
  geom_tufteboxplot(aes(y = value, color = as.factor(group))) +
  coord_flip()
```

![image](https://user-images.githubusercontent.com/12176934/88718111-7e1fdd00-d0ef-11ea-82d9-46de01ec6e53.png)

I don't know what error is happening internally, but adding the coord_flip() would work as a kludge.
