### ISSUE TITLE
geom_tufteboxplot whiskers extending to extremes

### ISSUE THREAD

**Issue by tjebo** [jrnold/ggthemes#118]
`geom_tufteboxplot` whiskers extend to extremes, and I don't find an option to change this behavior. Also, changing outlier shape, color, etc, does not result in any effect. 
``` r
library(ggplot2)
library(ggthemes)

ggplot(iris, aes(Species, Sepal.Length)) +
  geom_boxplot() 
```
Whisker extend to 1.5xIQR as usual:
![](https://i.imgur.com/NKmeY5a.png)

``` r
ggplot(iris, aes(Species, Sepal.Length)) +
  geom_tufteboxplot()
```
"Whisker" extend to extreme value
![](https://i.imgur.com/coJXcIh.png)

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tomhopper** [comment]
I think this is a nice catch.

In VDQI, Tufte describes first Spear's "range bar," in which the whiskers include (if I read Tufte correctly) the maximum and minimum values ("lowest to highest amount"), and then Tukey's box plot, where Tufte defines the ends of the whiskers as the "maximum" and "minimum." Tufte seems to build his _quartile plot_ (implemented as `geom_tufteboxplot()`) on the Tukey version but does not give any examples with outliers. It appears, at first reading, that Tufte's whiskers connect the IQR to the maximum and minimum values.

However, Tukey defines the _fences_ as lying, as @tjebo points out, `1.5 * IQR` from the median. The end points of the IQR are called _hinges_, and the whiskers connect hinges to the fences. Any points outside the fences are outliers and should, according to Tukey, be plotted individually. `geom_boxplot()` does this correctly, and it seems that Tufte intended to follow Tukey, so `geom_tufteboxplot()` should also follow this method.

**Comment by mattantaliss** [comment]
I found a solution for this: use `stat = "boxplot"`. Here's a reprex:
``` r
library(ggplot2)
library(ggthemes)

ggplot(iris, aes(Species, Sepal.Length)) +
  ggthemes::geom_tufteboxplot(stat = "boxplot")
```

![](https://i.imgur.com/dJ3YCTQ.png)

<sup>Created on 2020-05-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In my case, though, I had extreme outliers, and while I could also include `outlier.shape = NA`, that seems to only hide the outliers and the axis range does not automatically adjust to ignore them.

**Comment by tjebo** [comment]
@mattantaliss awesome! thanks

**Comment by jrnold** [comment]
@mattantaliss Thanks for the answer!
