### ISSUE TITLE
Please provide a gallery of the package

### ISSUE THREAD

**Issue by hope-data-science** [jrnold/ggthemes#119]
So many good themes you've designed, I wonder why you don't provide a gallery to display all these wonderful works. Or do I miss the info existed somewhere?

Thanks.

**Comment by brianrice2** [comment]
Here are some helpful pages I have used:
- https://mran.microsoft.com/snapshot/2017-02-04/web/packages/ggthemes/vignettes/ggthemes.html
- https://yutannihilation.github.io/allYourFigureAreBelongToUs/ggthemes/

**Comment by jrnold** [comment]
I used to have one, but now it is just distributed among the different help pages of the functions and the documentation website. I only have time to do the bare minimum maintenance on this package, so I likely won't be adding any new content like a gallery, but I'd accept a pull request.
