### ISSUE TITLE
geom_rangeframe is clipped by default

### ISSUE THREAD

**Issue by adamjhawkins** [jrnold/ggthemes#120]
By default:

![image](https://user-images.githubusercontent.com/36748901/82556824-6ada1980-9b62-11ea-9973-ffc61f2d0be4.png)

With `coord_cartesian(clip = 'off')`

![image](https://user-images.githubusercontent.com/36748901/82556800-5eee5780-9b62-11ea-8e2c-67e2522873e4.png)

As a geom, I guess it makes sense for it to be clipped, but it really doesn't look right where it's half the thickness of the ticks and clearly sliced in half as you can tell when looking at the rounded ends. If it's not possible for it to be somehow excluded from the clipping, could it be nudged a little so that it is fully inside the plot area?

**Comment by georgeblck** [comment]
Good on you to notice this. I always felt that `geom_rangeframe` and the ticks don't match up in a way and now I can fix it with `coord_cartesian(clip="off")`. 
Thanks

**Comment by jrnold** [comment]
Thanks for catching this! I'm adding this suggestion to the docs. I don't know how to solve it more completely: there is probably an approach to offset the x,y coords by the line, but I don't know how that would interact with coords.
