### ISSUE TITLE
Problems with theme_economist

### ISSUE THREAD

**Issue by valentinaandrade** [jrnold/ggthemes#132]
Hi! 👋🏼 
I can't reproduce the example put to use theme_economist. 

`dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
qplot(carat, price, data=dsamp, colour=clarity) + theme_economist(stata=TRUE) + scale_colour_economist(stata=TRUE) 
`

The error is `Error in theme_economist(stata = TRUE) : unused argument (stata = TRUE)`

**Comment by bbolker** [comment]
According to the [NEWS file](https://github.com/jrnold/ggthemes/blob/main/NEWS.md) this argument was removed in `ggthemes` version 4.0.0 (I have no idea why). If you really need this option you could install an older version of the package ...
