### ISSUE TITLE
Not enogh colors on palette "gdocs"

### ISSUE THREAD

**Issue by agustinggza** [jrnold/ggthemes#133]
Hi. 
Thank you very much for your package.
I am using the gdocs palette (which has 20 colors) to make a graph of 19 lines, like this " + scale_colour_gdocs()  "
but it only draws me 10 (I guess that's the default number).
How can I get it to draw 19 lines?
Thank you

**Comment by jrnold** [comment]
Updated colors and extended the scale to include 24 colors in  #db58832e353a8fc4c386dbbaec0002a9f3153b0c
