### ISSUE TITLE
images in package home page are broken

### ISSUE THREAD

**Issue by espinielli** [jrnold/ggthemes#140]
Images at the package home page, https://jrnold.github.io/ggthemes/, are broken

<img width="862" alt="Screenshot 2022-08-12 at 10 48 59" src="https://user-images.githubusercontent.com/891692/184319547-d78bd39a-20b5-446d-bb28-2fab9337f8dc.png">

**Comment by KayleeDavisGitHub** [comment]
This issue is a duplicate of #137

**Comment by jrnold** [comment]
Fixed by #162
