### ISSUE TITLE
Any alternatives?

### ISSUE THREAD

**Issue by JJ** [jrnold/ggthemes#147]
This is a dependence for a [CRAN package I maintain](https://github.com/JJ/dogesr), and today I received a message from CRAN stating that ggthemes is going to be archived, as well as all other packages that use it as a dependency.
So I guess this is mainly a question for other people who arrive here looking for mitigation measures, what are our options? Is there any real alternative, code-wise? Or just eliminate the dependence and all code that uses it?
Other than that, maybe someone has thought about forking, fixing the issues and releasing it, respecting the license?

**Comment by jrnold** [comment]
Sorry for the nonresponses. I'll update this to fix the results.

**Comment by jrnold** [comment]
Fixed by #150
