### ISSUE TITLE
Seems does not work with library(grid)

### ISSUE THREAD

**Issue by ns-1m** [jrnold/ggthemes#31]
It seems that ggthemes does not work properly with library(grid).

Here's the result. The first 2 graphs have themes from ggthemes.

![ggthemes_with_grid](https://cloud.githubusercontent.com/assets/646346/6477206/a40cecfe-c274-11e4-9e7e-0ba68126c2de.jpg)

**Comment by baptiste** [comment]
you might want to post a reproducible example, but seeing that grid is imported by ggplot2 and ggthemes, I find this unlikely.

**Comment by ns-1m** [comment]
Sorry, it actually works but a bit of the problem. Those 2 graphs does not have a themes in ggthemes examples.

However, It is not scaling up properly when the panel is not big enough. 

Here's the screenshot.

![ggthemes_not_scaling](https://cloud.githubusercontent.com/assets/646346/6477403/929e2c64-c277-11e4-9d11-2ca600fb7fe2.jpg)

**Comment by jrnold** [comment]
That's a `ggplot2` problem.  You need to adjust the font sizes when shrinking plots.

**Comment by jrnold** [comment]
You can use the `base_size` argument to any of themes to adjust the size of text and other items. I admit it's annoying to adjust the sizes to the size of the output, but that's the way that `ggplot2` works.

**Comment by ns-1m** [comment]
OK, Thanks.
