### ISSUE TITLE
Set significant figures for scale_x_tufte/scale_y_tufte

### ISSUE THREAD

**Issue by arnabarnabarnab** [jrnold/ggthemes#42]
A feature request rather than an issue *per se*.  It would be nice to set the number of significant figures for the breaks/ticks in the Tufte scales.

**Comment by Bcohn** [comment]
I'd be happy to take a stab at implementing this, what sort of option would you like to see, specifically? Would it maybe just be better to manually specify the breaks to be at even numbers using the breaks parameter?

**Comment by arnabarnabarnab** [comment]
The problem with setting the breaks to even numbers is it gets rid of the specific minimum/maximum of the Tufte Breaks.

I’ve been having a bit of a play, but am not really a proficient enough programmer to be able to implement this.   I think that two things would be useful:
1.  Setting the number of significant figures for the tick labels - essentially just applying signif(,digits=x) to the output
2.  Having the option to apply prettyNum() to the output to get rid of the (ugly) trailing zeroes.

A.

**Comment by jrnold** [comment]
You can get smarter by passing the function `smart_digits_format` to labels for the tufte scale (or any scale). It's in the package but I forgot to include any examples. 

If you have this, the formatting of the labels is poor.
```r
p <- ggplot(mtcars, aes(wt, mpg)) +
   geom_point()  +
   geom_rangeframe()  +
   theme_tufte() 

p + scale_x_tufte() + scale_y_tufte()
```
![stupidplot](https://cloud.githubusercontent.com/assets/123968/9277683/877e2d34-4260-11e5-8223-71713646d254.png)

But, adding the option `labels = smart_digits_format()` and it rounds the min/max labels to reasonable values.
```r
p + scale_x_tufte(labels = smart_digits_format()) +
   scale_y_tufte(labels = smart_digits_format())
```

![smartplot](https://cloud.githubusercontent.com/assets/123968/9277677/81fac49e-4260-11e5-9fc3-29f35b51f085.png)

**Comment by jrnold** [comment]
I'm leaving this open to remind myself to 

- [ ] Add smart_digits_format example
- [ ] Make `smart_digits_format` the default for the Tufte scales.

**Comment by dwanneruchi** [comment]
I can't seem to find  "scale_x_tufte()" or "scale_y_tufte()" - do these still exist within ggthemes?
