### ISSUE TITLE
axis.ticks.margin deprecated in latest ggplot2 version

### ISSUE THREAD

**Issue by Myfanwy** [jrnold/ggthemes#45]
Have been running into this error quite a bit: "axis.ticks.margin` is deprecated. Please set `margin` property  of `axis.text` instead"

Installation of ggplot2 is 1.0.1.9003, so might only be an issue when running the devtools installation of ggplot2 (devtools::install_github("hadley/ggplot2")?

**Comment by jrnold** [comment]
This should be fixed if you install the development version of `ggthemes`
```r
devtools::install_github("jrnold/ggthemes")
```
I'm waiting until the new `ggplot2` version pushes to CRAN to push the new `ggthemes`, because there are other changes to the backend of ggplot that are backwards incompatible.

**Comment by Myfanwy** [comment]
got it, sorry I didn't check that first!  Thanks.

**Comment by jrnold** [comment]
glad it's working!
