### ISSUE TITLE
facet labels are cut

### ISSUE THREAD

**Issue by VitorAguiar** [jrnold/ggthemes#47]
For example, look at the facet labels in:

ggplot(iris, aes(Sepal.Length, fill = Species)) + 
  geom_density() +
  facet_wrap(~Species, ncol = 1) + 
  theme_wsj()

**Comment by jrnold** [comment]
Thanks! I found the problem fixed it in the development version on github. I'm waiting to update CRAN until the new ggplot2 version comes out in December.
