### ISSUE TITLE
Weird result with scale_tufte

### ISSUE THREAD

**Issue by blaquans** [jrnold/ggthemes#49]
Hi

I've tried to use `scale_x_tufte()` on a dot plot. I've got a really weird result.

For my example, I generate a random dataframe : 

    library(ggplot2)
    library(magrittr)
    library(ggthemes)
    library(scales)
    library(gridExtra)
    set.seed(1234)
    N <- 5
    df <- data.frame(x = runif(N), y = letters[1:10])

The maximum value for x is 0.86 : 

    > df$x %>% max()
    [1] 0.8609154

When I draw a simple plot without specifying the scale for the x axis, I've got a good result : 

    plot1 <- df %>% 
    ggplot() + 
      geom_point(mapping = aes(x = x, y = reorder(y,x))) + 
      ggtitle("Simple plot")
    plot1

When I add `scale_x_tufte()` with option `labels = percent_format()`, I've got a wrong result setting the highest value to 100% instead of 86%

    plot2 <- plot1 + 
      scale_x_tufte(labels = percent_format()) + 
      ggtitle("Scale X Tufte")

I can solve the problem by adding the `limits` parameter to `scale_x_tufte()` 

    plot3 <- plot1 + 
      scale_x_tufte(labels = percent_format(), limits = c(0,1)) + 
      ggtitle("Scale X Tufte + Limits")

![scale_x_tufte](https://cloud.githubusercontent.com/assets/3227753/11533632/ff231da8-990a-11e5-985a-347ae19c7f24.png)

The default behaviour of `scale_x_tufte()` may lead many users to make wrong graphs.  

See my gist file to replicate this error : [scale_tufte.R](https://gist.github.com/blaquans/0ded2b99cd3f3c31304f)

    > R.version
                   _                           
    platform       x86_64-pc-linux-gnu         
    arch           x86_64                      
    os             linux-gnu                   
    system         x86_64, linux-gnu           
    status                                      
    major          3                           
    minor          2.2                         
    year           2015                        
    month          08                          
    day            14                          
    svn rev        69053                       
    language       R                           
    version.string R version 3.2.2 (2015-08-14)
    nickname       Fire Safety

**Comment by jrnold** [comment]
This seems to be caused by what ggplot2 passes to the scale. The scale only receives the limits, which may or may not correspond to the min and max values of interest. The Tufte scales had some hacks to try to get those values, but now it seems that there is no good way to handle all the cases. So I'm going to remove the Tufte scales. However, its feaures are still possible by using `extended_range_breaks` in the github version of `ggthemes`,
```{r}
plot2 <- plot1 + 
  scale_x_continuous(breaks = extended_range_breaks()(df$x), labels = percent_format()) + 
  ggtitle("Scale X Tufte")
plot2
```
Unlike `scale_x_tufte`, you need to explicitly give it the data for the breaks, but it's the only way to ensure it has the correct behavior.
