### ISSUE TITLE
Theme element 'text' has NULL property: margin, debug

### ISSUE THREAD

**Issue by englianhu** [jrnold/ggthemes#50]
I continue my research [Betting-Strategy-and-Model-Validation](https://github.com/englianhu/Betting-Strategy-and-Model-Validation/blob/master/Betting%20Strategy%20and%20Model%20Validation.Rmd) yesterday and noticed that wsj theme faced problem, kindly assist?
```diff
> (qplot(carat, price, data=dsamp, colour=cut)
+  + theme_wsj()
+  + scale_colour_wsj("colors6", "")
+  + ggtitle("Diamond Prices"))
- Error in FUN(X[[i]], ...) : 
-   Theme element 'text' has NULL property: margin, debug
```

**Comment by jrnold** [comment]
Are you using the dev version of **ggplot2**? There were a lot of backward-incompatible changes made to it. So you'll need to install the development version of **ggthemes** to work with it? 
```r
devtools::install_github("jrnold/ggthemes")
```

**Comment by englianhu** [comment]
downloaed latest version of ggplot2 and ggthemes but faced below error.
```diff
> ## Plot multiple layer and labeling y-axis on both left-right side.
> ## http://rpubs.com/kohske/dual_axis_in_ggplot2
> melted <- melt(res[c('Sess','Stakes','Return','PL')], id.vars=c('Sess'))
>
> ## ... + xlab('Year') + ylab("HKD ('000,000)")
> ## doesn't work in the ggthemes
> direct.label(ggplot(melted, aes(x=Sess, y=value/1000000, fill=variable,
color=variable)) + geom_bar(stat='identity', colour='black',
position='dodge') + xlab('Year') + ylab("HKD ('000,000)") +
theme_wsj(base_family='Verdana') + scale_colour_wsj('colors6', '') +
ggtitle("Annual Turnover and P&L HKD ('000,000)"),
list(last.bumpup,hjust=0.45,cex=0.65))
- Error in direct.label(ggplot(melted, aes(x = Sess, y = value/1e+06, fill
= variable,  :
-   lazy-load database
'C:/Users/Scibrokes/Documents/R/win-library/3.2/ggthemes/R/ggthemes.rdb' is
corrupt
```

2015年12月7日(月) 12:42 Jeffrey Arnold <notifications@github.com>:

**Comment by englianhu** [comment]
downloaed latest version of ggplot2 and ggthemes but faced below error.
```diff
> ## Plot multiple layer and labeling y-axis on both left-right side.
> ## http://rpubs.com/kohske/dual_axis_in_ggplot2
> melted <- melt(res[c('Sess','Stakes','Return','PL')], id.vars=c('Sess'))
> 
> ## ... + xlab('Year') + ylab("HKD ('000,000)")
> ## doesn't work in the ggthemes
> direct.label(ggplot(melted, aes(x=Sess, y=value/1000000, fill=variable, color=variable)) + geom_bar(stat='identity', colour='black', position='dodge') + xlab('Year') + ylab("HKD ('000,000)") + theme_wsj(base_family='Verdana') + scale_colour_wsj('colors6', '') + ggtitle("Annual Turnover and P&L HKD ('000,000)"), list(last.bumpup,hjust=0.45,cex=0.65))
- Error in direct.label(ggplot(melted, aes(x = Sess, y = value/1e+06, fill = variable,  : 
-   lazy-load database 'C:/Users/Scibrokes/Documents/R/win-library/3.2/ggthemes/R/ggthemes.rdb' is corrupt
```

**Comment by englianhu** [comment]
its works now without apply `directlabels::direct.label`.

**Comment by englianhu** [comment]
jrnold/ggthemesさん

LinkedInでつながってください。よろしくお願いします。

®γσ

®γσさんのリクエストを承認する: https://www.linkedin.com/e/v2?e=0-ik8409n3-u5&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=h6BAnbYi&invitationId=6100955049620496385








本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。メール購読を停止するには次のリンクをクリックしてください: https://www.linkedin.com/e/v2?e=0-ik8409n3-u5&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHjrGJUSbZsJQAAAVKryaiIe-fMH4asRMwX_CdAJnwqqcx8hr275ZD1bWNASWicR77dik1hJDB8DZovLGaOugkdvaUjFyiXbcKAEglio7C9Xmh4-FEdiwssKBsu7V7XyKVn8LW9Z3WP6CVW03IT9JHAZ697f7GTJ0aN-pQvV9Tx2C08bxTSbEIDLthzpO0VIdV5&eid=0-ik8409n3-u5


本メールはreply@reply.github.comに送信されています。

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ik8409n3-u5&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043.LinkedInおよびLinkedInのロゴは、LinkedInの登録商標です。

**Comment by englianhu** [comment]
®γσ Eng would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=kf9vj6-ikge5z1d-3k&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=h6BAnbYi&invitationID=6100955049620496385

View ®γσ Eng&#39;s profile: https://www.linkedin.com/e/v2?e=kf9vj6-ikge5z1d-3k&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=h6BAnbYi&invitationID=6100955049620496385





本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。購読停止: https://www.linkedin.com/e/v2?e=kf9vj6-ikge5z1d-3k&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=kf9vj6-ikge5z1d-3k&loid=AQEB-DLi-vknRgAAAVLKanwQbufuvVAdOwLFpoDuMvW12U6dR6Lre85qlamZb7EizqWiB2aL1YbgKlMpHiENX2t9qwl7hIoUfH8MdeIlBozRmgLtDTm5NgTYLfjXm5-tvWzos_KcV1JaqyiDjNZ-vrCGzrF8uQ1jP7A6N7JxN1RMEyWXlQNnJbxRfY4DDa4BVEbc

本メールはreply@reply.github.comに送信されています。

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=kf9vj6-ikge5z1d-3k&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043.LinkedInおよびLinkedInのロゴは、LinkedInの登録商標です。

**Comment by englianhu** [comment]
Hi jrnold/ggthemes,

I'd like to add you to my professional network on LinkedIn.

- ®γσ, Lian Hu

Confirm that you know ®γσ, Lian Hu: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=csCIDSV0&invitationId=6191937381755609088&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiu6ut1p2%7Eek








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iu6ut1p2-ek&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFzA0OPl4mjlwAAAVe4uch_hmIkqhou5o8mPoP-xEbCjUc1ImdZz5nnvGCWUhMrXTJlUBipPQfFhgoBEhzbSnY6qWNRkN2cFIDYKErNSIqmYd4n9WwEKzrGb9tYlX67-hRtSBzTiAQypU1eUazEzHcxPRM7OZa8LjGazp3fHluw2VOsDUSPPHmp0B6csoRV3rAE&eid=0-iu6ut1p2-ek


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iu6ut1p2-ek&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
