### ISSUE TITLE
Latest version throws 'ggthemes_data' not found if package not loaded

### ISSUE THREAD

**Issue by kieranrcampbell** [jrnold/ggthemes#55]
Minimal example:
```R
library(ggplot2)
ggplot(data.frame(x = 1:10, y = 2 * 1:10)) + geom_point(aes(x=x,y=y)) + ggthemes::theme_wsj()
``` 
fails with
`Error in ggthemes::theme_wsj() : object 'ggthemes_data' not found`

**Comment by jrnold** [comment]
Thanks! It's fixed in the github version. Since I just submitted to CRAN, I need to wait a bit to resubmit a fixed version.
