### ISSUE TITLE
ggthemes::ggthemes_data

### ISSUE THREAD

**Issue by kissmygritts** [jrnold/ggthemes#58]
I used to grab theme colors to use in a leaflet map with this line. It would give me a vector of RGB collar values.

```
pal <- as.character(ggthemes::ggthemes_data$gdocs)
```

Since the update I get an error.

```
Error: 'ggthemes_data' is not an exported object from 'namespace:ggthemes'
```

Do you have any work arounds to grab color palettes this way in the newest update?

**Comment by kissmygritts** [comment]
I see now that I can use this to return a vector of colors. Where `n` is the number of colors I want returned from the palette. This works for all the color palettes.

```
ggthemes::gdocs_pal()(n)
```

**Comment by jrnold** [comment]
That's a bug. I mad some changes with `ggthemes_data` and it seems that I forgot to export it it. I'll have it fixed in `dev` (installed via `install_github`) and it'll be fixed on CRAN next time I update it.

**Comment by jrnold** [comment]
Sorry for the bug. It's fixed now!
