### ISSUE TITLE
Adding a minimal theme

### ISSUE THREAD

**Issue by thecomeonman** [jrnold/ggthemes#60]
Something along these lines - 

```
minimalTheme = theme_set(theme_bw(12))
minimalTheme = theme_update(
   axis.ticks = element_blank(), 
   legend.position = 'none',
   strip.background = element_blank(), 
   panel.border = element_blank(), 
   panel.background = element_blank(), 
   panel.grid.major = element_line(color = 'grey80'), 
   panel.grid.minor = element_line(color = 'grey90'), 
   panel.border = element_blank()
)
```

**Comment by jrnold** [comment]
I think `theme_map` or `theme_solid` are similar. But, I'd be happy to accept a pull request.

**Comment by codoremifa** [comment]
Oops, I copied the wrong bit. I wanted to remove most of the settings but keep the grid lines. I've edited the original post.

**Comment by jrnold** [comment]
Sorry for not replying earlier. Thank you for suggesting it, but I'm going to close the issue. Right now, **ggthemes** is more or less in maintenance. So I'm trying to avoid adding many more themes unless they are sufficiently different than what has been implemented.
