### ISSUE TITLE
Add ylab to fivethirtyeight ggtheme?

### ISSUE THREAD

**Issue by ignacio82** [jrnold/ggthemes#61]
Is it possible to add a label to the y axis if you are using theme`fivethirtyeight`? I tried `ylab` but it does not work:

```
library(ggplot2)
library(ggthemes)
p2 <- ggplot(mtcars, aes(x = wt, y = mpg, colour = factor(gear))) +
  geom_point() +
  ggtitle("Cars")
p2 + geom_smooth(method = "lm", se = FALSE) +
  scale_color_fivethirtyeight("cyl") +
  theme_fivethirtyeight() + ylab('SOMETHING')
```

Thanks!

PS: I asked this question in [stackoverflow](http://stackoverflow.com/questions/36181990/add-ylab-to-ggplot-with-fivethirtyeight-ggtheme).

**Comment by jrnold** [comment]
Looks like aosmith on stackoverflow answered the question exactly like I would have!
