### ISSUE TITLE
base collor (for bars , points, etc) does not change without color or fill options

### ISSUE THREAD

**Issue by lucasmation** [jrnold/ggthemes#67]
Hey, awesome package. 

(Maybe this is a general ggplot2 question, not a ggthemes one, but lets see:) 

Is there a way to change the "default" color of graph content (bars, lines, points) when there is only one category being ploted, so the fill or color options are not present ?

For example: 

```
d <- data.frame(
  Ano=2000+5*0:10,
  A=factor("a"),
  Pop =c(6.1,6.5,6.9,7.3,7.7,8.0,8.3,8.6,8.9,9.1,9.3)
)

# plot1
d %>% ggplot(aes(x=Ano, y=Populacao       )) + geom_bar(stat="identity") +
  theme_economist()

# plot2
d %>% ggplot(aes(x=Ano, y=Populacao,fill=A)) + geom_bar(stat="identity") +
  theme_economist()

```
above, in plot1 the color of the bars is the ggplot2 defaul (grey). 

In plot2 the collor follow the collor palette, but with the disadvantage of adding a legend (which, of course, can be excluded with other commands)
In any case, adding a fill argument to a graph that has only one category will not be intuitive to users

**Comment by lucasmation** [comment]
Actually I just found the answer, , here: 

http://stackoverflow.com/questions/21174625/ggplot-how-to-set-default-color-for-all-geoms/21175042#21175042

**Comment by lucasmation** [comment]
you may want to consider addint default colors to the theme though. cheers

**Comment by jrnold** [comment]
I don't think I'll be adding that feature. There was another issue that asked for something similar, and maybe someone else will add something like it in a package. What I do provide in ggthemes is the object `ggthemes_data` which has the colors used in the various themes so that you can grab the right colors for use in geoms.

**Comment by kissmygritts** [comment]
@lucasmation use the following function to get the color you want. Replace economist with any of the provided color themes, replace 3 with the index of the color you want to use.
```
ggthemes::economist_pal()(8)[3]
```
