### ISSUE TITLE
geom_tufteboxplot doesn't dodge appropriately when an aesthetic is a factor

### ISSUE THREAD

**Issue by jgellar** [jrnold/ggthemes#68]
I have some code that I wrote a year or two ago that uses `geom_tufteboxplot()`, with a `colour` aesthetic that is a factor. Here is an example of what I want, using the `mpg` dataset:

```
p <- ggplot(mpg, aes(class, hwy))
p + geom_tufteboxplot(aes(colour = drv))
```

When I wrote my code a couple years ago, the above code would have produced multiple color-coded Tufte-style boxplots at each x location, and the boxplots would have been "dodged" so that they are not plotted on top of one another. I have since updated `ggthemes`, and now the boxplots are plotted on top of one another. Compare the above code to the following similar code, which correctly dodges the boxplots:
```
p + geom_boxplot(aes(colour = drv))
```
Was a bug introduced? Do you have any suggestions on how to "dodge" the colors with the current version of the package?

**Comment by jgellar** [comment]
Some more info...

The package version that I know worked for me previously was 2.1.2. I tried installing it with
```
packageurl <- "https://cran.r-project.org/src/contrib/Archive/ggthemes/ggthemes_2.1.2.tar.gz"
install.packages(packageurl, repos = NULL, lib = tmplib, type = "source")
```
but i got some errors, I think related to the old `proto` package used with `ggplot2`.

**Comment by jgellar** [comment]
I was able to dodge the boxplots by setting `position = "dodge"`. I do think that you should make this the default when a factor is used as an aesthetic, which it is for `geom_boxplot` and which it used to be for `geom_tufteboxplot`.

Another issue that I am having is with the legend. The default legend in previous versions of `ggthemes` was a straight line, now it is a mini boxplot (non Tufte-style, a traditional boxplot). How can I change it back to the line, which would look closer to what is actually being plotted as the Tufte-style boxplot? I have tried a number of options using `guide_legend`, so far the best thing I have come up with is:
```
    p + guides(colour = guide_legend(override.aes = list(size=.5, fill = "white")))
```
which makes a small boxplot as the legend symbol, will normal-sized lines (the default lines are way too thick) and fills it in with white (as opposed to the default, which is black). However, I would much prefer a straight horizontal line as opposed to the boxplot.

**Comment by jgellar** [comment]
okay, i found a hack around to add lines, but this was not intuitive. IMO, `geom_tufteboxplot` should use straight lines for the legend, not traditional boxplots.
```
ggplot(mpg, aes(class, hwy)) +
  geom_line(aes(y = median(hwy), colour = drv)) +
  geom_tufteboxplot(aes(colour = drv), position = "dodge", show.legend = FALSE)
```

**Comment by jrnold** [comment]
Sorry for the delay. I'll take a look at it. The new version of `ggplot2` changed the entire backend of the geoms (it no longer depends on `proto`), so I had to rewrite them. When I have some time, I'll take a look at implementing your suggestions.

**Comment by jrnold** [comment]
Thanks! I've now set "dodge" as the default position for `geom_tufteboxplot`.
