### ISSUE TITLE
geom_rangeframe() does not work with dev/ggplot2 

### ISSUE THREAD

**Issue by coulmont** [jrnold/ggthemes#70]
"Error in zero_range(from) : x must be length 1 or 2" when using geom_range with the development version of ggplot2

**Comment by coulmont** [comment]
Example of issue with the current dev/ggplot2 and dev/ggthemes : 

mtcars$carb <- as.factor(mtcars$carb)
p <- ggplot(mtcars, aes(x = wt, y = mpg, group=carb, color=carb)) +
  geom_point() +
  ggtitle("Cars")
p + geom_rangeframe() +
  theme_tufte() + 
  scale_x_continuous(breaks = extended_range_breaks()(mtcars$wt)) +
  scale_y_continuous(breaks = extended_range_breaks()(mtcars$mpg))
Error in check.length(gparname) : 
  'gpar' element 'fontsize' must not be length 0

**Comment by jrnold** [comment]
Thanks. It seems to be working now.
