### ISSUE TITLE
Panel.margin and legend.margin deprecated in ggplot2 2.2.0 

### ISSUE THREAD

**Issue by madsboending** [jrnold/ggthemes#73]
Hi

Great package, thanks!

After updating to ggplot2 2.2.0 I get following warnings when using theme_economist_white()
Warning messages:
1: `panel.margin` is deprecated. Please use `panel.spacing` property instead 
2: `legend.margin` must be specified using `margin()`. For the old behavior use legend.spacing 

ggplot(mpg, aes(hwy))+geom_density()+theme_economist_white() recreates the warnings

**Comment by jrnold** [comment]
Thanks! I had that fixed in github branch, but was waiting for 2.2.0 to push to CRAN and I had missed that it was updated on CRAN. I'll be uploading a new version of ggthemes to CRAN soon.
