### ISSUE TITLE
[Request] theme_sol

### ISSUE THREAD

**Issue by kendonB** [jrnold/ggthemes#75]
This is a popular stata scheme, similar to theme_minimal, but with no grid and with only the bottom x-axis and left y-axis lines. 

See here: http://www.fight-entropy.com/2013/01/prettier-graphs-with-less-headache-use.html

**Comment by kendonB** [comment]
This is actually almost theme_cowplot. You could do it with:

```
theme_sol <- function() theme_cowplot() +
  theme(strip.background = element_blank())
```

**Comment by jrnold** [comment]
Thanks for the suggestion. Both the sol theme and cowplot scheme look pretty nice. But since the derived sol theme is so similar to some other themes, I don't know if it different enough to be worth including here.
