### ISSUE TITLE
Error in eval(expr, envir, enclos) : could not find function "eval". ggphylo, ggplot

### ISSUE THREAD

**Issue by FranciscoMenendez** [jrnold/ggthemes#79]
When installing ggphylo using githubinstall I get the following error. I've tried installing the latest version of ggplot from CRAN and github but the error persists.

     `> githubinstall('gjuggler/ggphylo')
    Suggestion:
     - gjuggler/ggphylo  Phylogenetic plots for R and ggplot
    Do you want to install the package (Y/n)?  y
    Downloading GitHub repo gjuggler/ggphylo@master
    from URL https://api.github.com/repos/gjuggler/ggphylo/zipball/master
    Installing ggphylo
    "C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  INSTALL  \
      "C:/Users/Francisco/AppData/Local/Temp/RtmpOAP5Si/devtools2fd032474d9b/gjuggler-ggphylo-745eb49"  \
      --library="C:/Users/Francisco/Documents/R/win-library/3.2" --install-tests 

    * installing *source* package 'ggphylo' ...
    ** R
    ** inst
    ** preparing package for lazy loading
    Warning: package 'ape' was built under R version 3.2.5
    Warning: package 'ggplot2' was built under R version 3.2.5
    Warning: package 'gridExtra' was built under R version 3.2.5
    Warning: package 'proto' was built under R version 3.2.5
    Warning: package 'plyr' was built under R version 3.2.5
    Error in eval(expr, envir, enclos) : could not find function "eval"
    Error : unable to load R code in package 'ggphylo'
    ERROR: lazy loading failed for package 'ggphylo'
    * removing 'C:/Users/Francisco/Documents/R/win-library/3.2/ggphylo'
    Error: Command failed (1)`

**Comment by jrnold** [comment]
This doesn't appear to be a problem with `ggthemes`.  My best guess as to your problem is that you do not have the most recent versions of the packages installed. The current version of R is 3.3.2, https://cran.r-project.org/, so even if you update packages you'll get only old versions for some packages.
