### ISSUE TITLE
GraphPad Prism theme?

### ISSUE THREAD

**Issue by Guilz** [jrnold/ggthemes#80]
Hello there,

Very nice collection of themes!

If I may suggest, it would be useful to have a theme similar to the default in [GraphPad Prism](http://www.graphpad.com/scientific-software/prism/):

![image](https://cloud.githubusercontent.com/assets/9656546/23679755/24095e4c-0346-11e7-9ec3-ff31449c3d1f.png)

**Comment by jrnold** [comment]
Thanks! If you'd like it in ggthemes, I'd be happy to accept a pull request.

**Comment by Guilz** [comment]
I submitted this as an issue / feature request because I have no idea (yet) how to make a ggplot2 theme (otherwise, I would have proposed it as a PR). I will eventually figure out how to do that, but I haven't much time to dedicate to this so that might be in a far future. I thought someone else who knows how to make a theme could be much faster than me. :-)

**Comment by jrnold** [comment]
Checkout http://docs.ggplot2.org/current/theme.html. The most difficult thing is the iterative process of getting it look like you want. At this point, `ggthemes` is pretty stable. I maintain it, but don't add much unless I have a strong reason to do so.

**Comment by Guilz** [comment]
Thank you for the reference. I'll have a look, and maybe come up with something, but I don't know when.
