### ISSUE TITLE
Different thickness axes after using geom_rangeframe

### ISSUE THREAD

**Issue by TarjinderSingh** [jrnold/ggthemes#83]
Hello! 

I am trying to use geom_rangeframe with other themes to truncate axes, as described [here](http://stackoverflow.com/questions/28423322/ggplot2-how-to-make-axis-line-end-at-the-last-tick), but when I run the following command, the x-axis appears to be thicker than the y-axis. Is there a way of making them uniformly sized? Minor thing, but it'll be nice to know why... 

Thanks!

```
qplot(mpg, wt, data=mtcars) + 
  geom_rangeframe(data=data.frame(x=c(10, 35), y=c(0, 6)), aes(x, y)) + 
  theme_bw(base_size = 16) + 
  theme(legend.background = element_blank(), legend.key = element_blank(), 
        panel.background = element_blank(), panel.border = element_blank(), 
        strip.background = element_blank(), plot.background = element_blank(), 
        axis.line = element_blank(), panel.grid = element_blank()) +
  scale_x_continuous(limits = c(10, 35)) +
  scale_y_continuous(limits = c(0, 6)) 
```

**Comment by flying-sheep** [comment]
i have the same problem, but the data in the grob object doesn’t indicate that the width is broken. using #84:

```r
library(purrr)
library(ggplot2)
library(ggthemes)

# get a grob by name
gget <- function(grobs, prefix) {
  re <- paste0('^', prefix, '\\.')
  grobs %>% detect(. %>% .$name %>% grepl(re, .))
}

gg <- qplot(1:5, sqrt(1:5)) +
  geom_rangeframe() +
  theme_map()  # minimal appearance

ggplotGrob(gg)$grobs %>%
  gget('panel-1')         %>% .$children %>%
  gget('geom_rangeframe') %>% .$children %>%
  map('gp') %>% map('lwd')
```

**Comment by flying-sheep** [comment]
I tried to replicate it in a smaller example, but the clip path doesn’t appear:

https://gist.github.com/flying-sheep/0f6079360071ca2f76da047ed93f40ac

**Comment by flying-sheep** [comment]
@TarjinderSingh why did you close this?
