### ISSUE TITLE
New theme arguments

### ISSUE THREAD

**Issue by ptoche** [jrnold/ggthemes#87]
The ``theme()`` function has a few new arguments, a couple of which may be worth adding to ``ggthemes``. I'm thinking about ``plot.subtitle`` and ``plot.caption``

Something for the to-do list perhaps...

**Comment by ptoche** [comment]
I'm getting an error with ``theme_stata`` that I didn't get before:

    Error in if (theme$panel.ontop) { : argument is of length zero

Also (not sure if that's new), the theme economist gives an ugly horizontal line at the horizontal axis with overlapping labels for:

    ggplot(mtcars, aes(x = cyl)) + geom_bar()

Also, for the economist theme, ``axis.text.y = element_text(hjust = 1,...`` works better for numbers along the vertical axis, while ``axis.text.y = element_text(hjust = 0,...`` works well for strings. I have checked that indeed that is how The Economist does it. This suggests setting ``hjust`` with  a conditional on whether the labels are numeric or character/factor...

Quickly tested the following: "theme_base", "theme_calc", "theme_economist", "theme_excel", "theme_few", "theme_fivethirtyeight", "theme_gdocs", "theme_hc", "theme_par", "theme_pander", "theme_solarized", "theme_stata", "theme_tufte", "theme_wsj"

**Comment by jrnold** [comment]
I can't reproduce the error: `error in if (theme$panel.ontop) { : argument is of length zero`. Can you provide more info?

**Comment by jrnold** [comment]
Since the `theme` is independent of the `data`, it would be hard to directly include that condition. I could maybe add an arg that would set `hjust` to 0 or 1; it wouldn't be that much more convenient than manually setting it with `theme`, but would act like documentation as much as anything.

**Comment by jrnold** [comment]
I don't have any real plans for adding those new args for themes in the near future. If you find the settings that work well for a particular theme, I'd love a pull request.

**Comment by jrnold** [comment]
> Also (not sure if that's new), the theme economist gives an ugly horizontal line at the horizontal axis with overlapping labels for:

I'm not sure what you're referring to here. The horizontal line is part of the theme; probably not the best for a bar chart, but that's what additional customization can be used for.

**Comment by ptoche** [comment]
The Economist's theme: 

![rplot](https://user-images.githubusercontent.com/6339274/38232833-092d7c68-374b-11e8-8f75-5a5a07a75821.png)

**Comment by ptoche** [comment]
Further info about the ``hjust`` comment:

    ggplot(data = mtcars[c(1:8),], aes(x = mpg, y = row.names(mtcars)[1:8])) + geom_point() + theme_economist() + theme(axis.text.y = element_text(hjust = 1))

![rplot01](https://user-images.githubusercontent.com/6339274/38233244-7ce04e6e-374c-11e8-9010-c1146d3081b1.png)


versus 

    ggplot(data = mtcars[c(1:8),], aes(x = mpg, y = row.names(mtcars)[1:8])) + geom_point() + theme_economist() + theme(axis.text.y = element_text(hjust = 0))

![rplot02](https://user-images.githubusercontent.com/6339274/38233254-8524e6c0-374c-11e8-8d9e-e6d02d1c6b54.png)

**Comment by ptoche** [comment]
Another comment in passing, the Stata theme doesn't work well with long labels on the y-axis. Stata provides the ``angle(h)`` option to set the labels to horizontal, which can be obtained with ``theme(axis.text.y = element_text(angle = 0))``.  Perhaps a one-liner you can add to the readme file. Just a thought.

**Comment by jrnold** [comment]
Those examples seem to be cases where the user has to do some additional formatting to polish the plot using the `theme` function. That's the case in many plots. I don't see anything about these particular examples that's much different than the typical workflow with plots.

**Comment by ptoche** [comment]
You're right, so I closed the issue.
