### ISSUE TITLE
Shapes from scale_shape_circlefill don't render in pdf. 

### ISSUE THREAD

**Issue by eliocamp** [jrnold/ggthemes#90]
The scale works wonderfully when displaying in RStudio but when knited to a pdf they break.

![image](https://user-images.githubusercontent.com/8617595/39206710-87bb6ec0-47d4-11e8-98fe-c3d0bb28022c.png)

I don't know if this is a bug that can be resolved by `ggthemes` or a limitation of the pdf format.

**Comment by jrnold** [comment]
It's almost certainly the PDF output. If it is the size of the fonts or other elements you'll have to adjust them to fit the size of the pdf.  That's one reason for the `base_size` argument for all fonts.

**Comment by jrnold** [comment]
It may be that the font that's being used doesn't support those characters.

**Comment by eliocamp** [comment]
You're right. This was solved by using cario_pdf() as dev so it embeds the fonts -> https://stackoverflow.com/questions/36453126/embedding-fonts-in-ggplot2-charts-in-rmarkdown-documents

Thanks.
