### ISSUE TITLE
theme_few missing axis labels and gridlines

### ISSUE THREAD

**Issue by chriscesar** [jrnold/ggthemes#91]
Hi,

Title says it all really.  Using ggthemes_3.5.0 with theme_few(), the package no longer prints axis labels and gridlines.  Other functions (e.g. theme_tufte) work fine.

Running 32 bit R version 3.5.0 (2018-04-23).

Many thanks,

Chris

**Comment by chriscesar** [comment]
'standard' version:
![image](https://user-images.githubusercontent.com/3082834/40066559-4b9cb4e2-585c-11e8-81f1-78312e6f47e6.png)

theme_few() version:
![image](https://user-images.githubusercontent.com/3082834/40066598-69028ee4-585c-11e8-8057-feaf9ba4d278.png)

theme_stata() version:
![image](https://user-images.githubusercontent.com/3082834/40066869-efb7da16-585c-11e8-96f1-aa3cbf2247a7.png)

**Comment by lozalojo** [comment]
Same exact problem, rolling back to 3.4.2 solves the problem.

**Comment by jrnold** [comment]
Sorry. Fixed in the github version; I'll push to CRAN soon. I had updated the colors to fix #89  and changed the color names which screwed up the theme.
