### ISSUE TITLE
panel border with theme_few

### ISSUE THREAD

**Issue by brunoasm** [jrnold/ggthemes#94]
Hi, I recently updated my R version after a long time and some scripts that I had using theme_few() are  rendering plots differently.

The most notable difference is that the panel border that used to exist is now gone. Not a big deal to add it to these plots, but I would just like to confirm that this is the new intended behavior.

I am not sure what version I was using before, but I have 3.5.0 now.

Thanks.

**Comment by jrnold** [comment]
Yes, there is a bug in it. I've fixed it in the development version (which requires the newest version of ggplot2) which you can install from github:
```
install_github("jrnold/ggthemes")
```

A fixed version of ggthemes should be on CRAN soon - it's in the pipeline.

**Comment by brunoasm** [comment]
Great, thanks!

**Comment by jrnold** [comment]
New version accepted to CRAN. It'll be up in the next day or so.
