### ISSUE TITLE
Classic tableau palettes

### ISSUE THREAD

**Issue by luca-scr** [jrnold/ggthemes#96]
It seems that classic tableau palettes have order reversed. 
See for instance the following plots:

```
library("ggthemes")
library("scales")
pal <- tableau_color_pal("Classic 10")
show_col(pal(attr(pal, "max_n")))
pal <- tableau_color_pal("Classic 20")
show_col(pal(attr(pal, "max_n")))
```

**Comment by jrnold** [comment]
Thanks! It's fixed in the github version. I should push a patch to CRAN soonish.
