### ISSUE TITLE
reverse  "Orange-Blue Diverging" or "Orange-Blue-White Diverging"

### ISSUE THREAD

**Issue by fissehab** [jrnold/ggthemes#98]
Is it possible to reverse the Orange-Blue Diverging or Orange-Blue-White Diverging palettes in scale_color_gradient2_tableau?

**Comment by jrnold** [comment]
You can set `trans = "reverse"` to reverse the scale.
```r
df <- data.frame(
  x = runif(100),
  y = runif(100),
  z1 = rnorm(100),
  z2 = abs(rnorm(100))
)
p <- ggplot(df, aes(x, y)) + geom_point(aes(colour = z2))

p + scale_colour_gradient2_tableau() + ggtitle("Original")
p + scale_colour_gradient2_tableau(trans = "reverse") + ggtitle("Reversed")

```
![image](https://user-images.githubusercontent.com/123968/52920828-d67d6900-32c5-11e9-90d2-c40e3f5a5746.png)

![image](https://user-images.githubusercontent.com/123968/52920816-bcdc2180-32c5-11e9-8046-5d76e84b0889.png)
